import { GetStaticProps } from 'next';
import Head from 'next/head';
import dbConnect from '../utils/dbConnect';
import Resource from '../models/Resource';
import Product from '../models/Product';
import HeroContent from '../components/home/HeroContent';
import HomeBanner from '../components/home/HomeBanner';
import Popular from '../components/home/Popular';
import ChefSpecial from '../components/home/ChefSpecial';
import Speciality from '../components/home/Speciality';
import Footer from '../components/footer/Footer';

export default function Home({ heroContent, popularContent, chefContent, products }) {
	if (!heroContent || !popularContent || !chefContent || !products) {
		return <h1>No content</h1>;
	}

	return (
		<div>
			<Head>
				<title>Resturant</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<div className="">
				<div className="">
					<HeroContent heroContent={heroContent} />
				</div>
				<div>
					<HomeBanner />
				</div>
				<div>
					<Popular popularContent={popularContent} />
				</div>
				<div>
					<ChefSpecial chefContent={chefContent} />
				</div>
				<div className="px-5 md:px-12 bg-purple-100 mt-12 sm:mt-16 lg:mt-48 max-w-md mx-auto sm:max-w-xl lg:max-w-full">
					<h3 className=" pt-6 lg:ml-4 text-md font-bold  uppercase">Our specialities</h3>

					<Speciality products={products} />
				</div>
				<div>
					<Footer />
				</div>
			</div>
		</div>
	);
}

export const getStaticProps = async (ctx) => {
	await dbConnect();
	const res = Resource.find({ category: 'hero' });
	const res1 = Resource.find({ category: 'popular' });
	const res2 = Resource.find({ category: 'chefs special' });
	const [ heroRes, popularRes, chefRes ] = await Promise.all([ res, res1, res2 ]);
	const heroContent = JSON.parse(JSON.stringify(heroRes));
	const popularContent = JSON.parse(JSON.stringify(popularRes));
	const chefContent = JSON.parse(JSON.stringify(chefRes));

	const pres = await Product.find({}).limit(10);
	const products = JSON.parse(JSON.stringify(pres));

	return {
		props: {
			heroContent,
			popularContent,
			chefContent,
			products
		},
		revalidate: 5
	};
};
