import { GetStaticProps } from 'next';
import Head from 'next/head';
import dbConnect from '../utils/dbConnect';
import Resource from '../models/Resource'
import HeroContent from '../components/home/HeroContent';

export default function Home({ heroContent }: any) {
	console.log(heroContent);

	return (
		<div>
			<Head>
				<title>Resturant</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<div>
				<HeroContent heroContent={heroContent} />

			</div>
		</div>
	);
}

export const getStaticProps: GetStaticProps = async (ctx) => {
	await dbConnect();
	const res = Resource.find({ category: 'hero' })
	const [heroRes] = await Promise.all([res]);
	const heroContent = JSON.parse(JSON.stringify(heroRes));

	return {
		props: {
			heroContent
		}
	}

}
