import { Fragment } from 'react';
import Head from 'next/head';
import Image from 'next/image';
import CheckIcon from '../public/iconmonstr-check-mark-8.svg';

export default function paymentSuccess() {
	return (
		<Fragment>
			<Head>
				<title>Payment Success</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div className="flex h-screen  ">
				<div className=" m-auto block sm:flex space-x-6 items-center text-3xl font-bold text-green-700 ">
					<h1 className=""> Payment successful</h1>
					<div className="hidden sm:block sm:ml-7 bg-green-700 px-2 py-2 rounded-full">
						<Image src={CheckIcon} alt="Success icon" />
					</div>
				</div>
			</div>
		</Fragment>
	);
}
