import Sidebar from '../../components/dashboard/Sidebar';
import CreateProduct from '../../components/dashboard/CreateProduct';
import CreateResource from '../../components/dashboard/CreateResource';
import Head from 'next/head';
import { useRouter } from 'next/router';
import { withPageAuthRequired } from '@auth0/nextjs-auth0';

export default withPageAuthRequired(function Dashboard({ }) {
	const { query } = useRouter();


	return (
		<div>
			<Head>
				<title>Dashboard</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div className="flex">
				<Sidebar />
				<main>

					{query.query === 'create-product' && <CreateProduct />}
					{query.query === 'create-resource' && <CreateResource />}

				</main>

			</div>
		</div>
	);
});
